#!/bin/bash

function checkunison() {
  
  case $? in
      0)
        notify-send -u low "$1: Successful sync."
          ;; 
      1)
        zenity --question --text "$1: All file transfers were successful. Some files were skipped. Show the log?"
        if [ "$?" -ne 1 ]; then
          cat $2 | zenity --text-info --width 800 --height 1000 ;
        fi
          ;; 
      2)
        zenity --question --text "$1: Non-fatal failures during file transfer. Show the log?"
        if [ "$?" -ne 1 ]; then
          cat $2 | zenity --text-info --width 800 --height 1000 ;
        fi
          ;;
      3)
        zenity --question --text "$1: Fatal error occurred! Show the log?"
        if [ "$?" -ne 1 ]; then
          cat $2 | zenity --text-info --width 800 --height 1000 ;
        fi
        exit 1
          ;; 
      *)
        zenity --question --text "$1: Unknown exit code. Show the log?"
        if [ "$?" -ne 1 ]; then
          cat $2 | zenity --text-info --width 800 --height 1000 ;
        fi
        exit 1
          ;; 
  esac
}

function syncdev() {
  echo "starting synchronisation of developing"
  unison gausussyncdev >> $1 2>> $1
  checkunison "dev" $1
  echo "finished"
}

function syncdoc() {
  echo "starting synchronisation of documents/tex"
  unison gausussyncdoc >> $1 2>> $1
  checkunison "doc" $1
  echo "finished"
}

function syncall() {
  syncdev $1
  syncdoc $1
  exit 0
}

LOG="/tmp/synclog"

date > $LOG

response=$(zenity --height=250 --list --text "Synchonization Selection:" --checklist --column=Boxes --column=Selections \
   FALSE all \
   TRUE  dev \
   FALSE doc  --separator=':')

if [ -z "$response" ] ; then
   echo "No selection"
   exit 1
fi

IFS=":" ; for word in $response ; do 
   case $word in
      all) syncall $LOG ;;
      dev) syncdev $LOG ;;
      doc) syncdoc $LOG ;;
   esac
done
